bind_host: 0.0.0.0
bind_port: 3000
beta_bind_port: 0
users:
- name: root
  password: $2y$10$9BEVAeeW6cYS045JkQdSl.qX7MRBztg0VICV5tBZZIKegkmnk7qDq
auth_attempts: 5
block_auth_min: 15
http_proxy: ""
language: ""
rlimit_nofile: 0
debug_pprof: false
web_session_ttl: 720
dns:
  bind_hosts:
  - 0.0.0.0
  port: 5353
  statistics_interval: 1
  querylog_enabled: true
  querylog_file_enabled: true
  querylog_interval: 1
  querylog_size_memory: 1000
  anonymize_client_ip: false
  protection_enabled: true
  blocking_mode: null_ip
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_response_ttl: 10
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  ratelimit: 0
  ratelimit_whitelist: []
  refuse_any: false
  upstream_dns:
  - '#https://doh-139e5817-openwrt.doh.pub/dns-query'
  - '#tls://dot-139e5817.dot.pub'
  - '#116.116.116.116'
  - '#221.5.88.88'
  - '#https://223.5.5.5/dns-query'
  - '#https://doh.pub/dns-query'
  - 117.50.10.10
  - 119.29.29.29
  - 1.0.0.1
  - 8.8.8.8
  - 208.67.222.222
  - https://dns.google/dns-query
  - 117.50.10.10
  - '#[/xiangshangyx.com/]8.8.8.8'
  - '[/netflix.com/]tcp://159.75.94.25:5353'
  - '[/nflxvideo.net/]tcp://159.75.94.25:5353'
  - '[/nflxso.net/]tcp://159.75.94.25:5353'
  - '[/amazonaws.com/]tcp://159.75.94.25:5353'
  - '[/nflxvideo.net/]tcp://159.75.94.25:5353'
  - '[/fast.com/]tcp://159.75.94.25:5353'
  - '[/netflix/]tcp://159.75.94.25:5353'
  - '[/netflix.com/]tcp://159.75.94.25:5353'
  - '[/netflix.net/]tcp://159.75.94.25:5353'
  - '[/nflxso.net/]tcp://159.75.94.25:5353'
  - '[/nflxext.com/]tcp://159.75.94.25:5353'
  - '[/nflximg.com/]tcp://159.75.94.25:5353'
  - '[/nflximg.net/]tcp://159.75.94.25:5353'
  - '[/nflxvideo.net/]tcp://159.75.94.25:5353'
  - '[/netflixdnstest0.com/]tcp://159.75.94.25:5353'
  - '[/netflixdnstest1.com/]tcp://159.75.94.25:5353'
  - '[/netflixdnstest2.com/]tcp://159.75.94.25:5353'
  - '[/netflixdnstest3.com/]tcp://159.75.94.25:5353'
  - '[/netflixdnstest4.com/]tcp://159.75.94.25:5353'
  - '[/netflixdnstest5.com/]tcp://159.75.94.25:5353'
  - '[/netflixdnstest6.com/]tcp://159.75.94.25:5353'
  - '[/netflixdnstest7.com/]tcp://159.75.94.25:5353'
  - '[/netflixdnstest8.com/]tcp://159.75.94.25:5353'
  - '[/netflixdnstest9.com/]tcp://159.75.94.25:5353'
  - '[/raw.githubusercontent.com/]1.0.0.1'
  - '[/baidu.com/]116.116.116.116'
  upstream_dns_file: ""
  bootstrap_dns:
  - 116.116.116.116
  - 221.5.88.88
  all_servers: true
  fastest_addr: false
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts:
  - version.bind
  - id.server
  - hostname.bind
  cache_size: 0
  cache_ttl_min: 0
  cache_ttl_max: 0
  bogus_nxdomain: []
  aaaa_disabled: false
  enable_dnssec: false
  edns_client_subnet: false
  max_goroutines: 300
  ipset: []
  filtering_enabled: true
  filters_update_interval: 24
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: false
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  rewrites: []
  blocked_services: []
  local_domain_name: lan
  resolve_clients: true
  local_ptr_upstreams: []
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 784
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: false
  strict_sni_check: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
filters:
- enabled: true
  url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
  name: AdGuard Simplified Domain Names filter
  id: 1
- enabled: true
  url: https://adaway.org/hosts.txt
  name: AdAway
  id: 2
- enabled: false
  url: https://www.malwaredomainlist.com/hostslist/hosts.txt
  name: MalwareDomainList.com Hosts List
  id: 4
- enabled: false
  url: https://hosts.nfz.moe/basic/hosts
  name: neoHosts basic
  id: 1575618241
- enabled: false
  url: http://sbc.io/hosts/hosts
  name: StevenBlack host basic
  id: 1575618242
- enabled: false
  url: http://sbc.io/hosts/alternates/fakenews-gambling-porn-social/hosts
  name: StevenBlack host+fakenews + gambling + porn + social
  id: 1575618243
- enabled: true
  url: https://cdn.jsdelivr.net/gh/privacy-protection-tools/anti-AD/anti-ad-easylist.txt
  name: anti-AD(Adblock+neohosts+yhosts+cjxlist+adhlist)
  id: 1577113202
- enabled: false
  url: https://anti-ad.net/easylist.txt
  name: an
  id: 1608373928
- enabled: true
  url: https://someonewhocares.org/hosts/zero/hosts
  name: Dan Pollock's List
  id: 1608373929
- enabled: true
  url: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext
  name: Peter Lowe's List
  id: 1608373930
whitelist_filters: []
user_rules:
- '@@||port.aiastia.com^$important'
- '@@||vps.aiastia.com^$important'
- '@@||stats.uptimerobot.com^$important'
- ""
dhcp:
  enabled: false
  interface_name: ""
  dhcpv4:
    gateway_ip: ""
    subnet_mask: ""
    range_start: ""
    range_end: ""
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false
clients: []
log_compress: false
log_localtime: false
log_max_backups: 0
log_max_size: 100
log_max_age: 3
log_file: ""
verbose: false
schema_version: 10
